### PR TITLE
Remove token write permissions workaround

### LINKED ISSUE #195: Remove token write permissions workaround
Remove the workaround here as should no longer be required: https://github.com/calyptia/api/blob/5fef9fa268ce07cefece664a5e19d911f17c8418/scripts/setup-tests.sh#L13-L18

### PR DESCRIPTION
**Pull request by gabrielbussolo**
# Summary of this proposal

Close #195 

## Issue(s) number(s)

*Disclaimer: Please do not create a Pull Request without creating an issue first.*

## Checklist for submitter

- [ ] My PR has a related issue/bug number.
- [ ] My PR provides tests
  - [ ] Integration tests are added/passes
  - [ ] Unit tests are added/passes
  - [ ] End-to-end tests added/passes
  - [ ] Static code check added/passes
  - [ ] Linting on documentation added/passes
  - [ ] Does not affect code coverage stats
- [ ] My PR requires updating dependencies
- [ ] My PR has the documentation changes required.

## Checklist for reviewer

- [ ] The proposal fixes a bug/issue or implements a new feature that is well described.
- [ ] The proposal has sufficient test cases that covers the changes.
  - [ ] If changes an API, it does not break backwards compatibility (-1 major version).
- [ ] If integration is required, the proposal has integration tests.
- [ ] The proposal does not break coverage stats
- [ ] The proposal has the required documentation changes.

## Backport

- [ ] Backport to the latest stable release.

### CODE REVIEW

**Comment by patrick-stephens** [comment]
I don't think that is merged yet plus there are other updates to the workflows required.

**Comment by gabrielbussolo** [comment]
I noticed you changed this file permission on the pr https://github.com/calyptia/cloud/pull/425 to 0644 but the actual file permission[ today is 600](https://github.com/calyptia/cloud/blob/main/cmd/cloud/main.go#L49) is that correct?

**Comment by patrick-stephens** [comment]
Yeah it stops a lot of weird issues and no reason to lock it down anyway

**Comment by gabrielbussolo** [comment]
> I don't think that is merged yet plus there are other updates to the workflows required.

Yeah, I was checking and we still create this `defaultToken` [as you can see](https://github.com/calyptia/cloud/blob/757434e7b72dc759564781f033a9ae9fafedb13c/cmd/cloud/main.go#L197-L203) so I will close this PR for now @patrick-stephens

**Pull request closed without merging**
