### PR TITLE
Add auth0 variables to the test workflow

### LINKED ISSUE #193: Add the auth0 test variables to the api workflow
# Bug Report

## Describe the bug

Intends to fix the tests that r blocking the pipeline as related on [calyptia/cloud#790](https://github.com/calyptia/cloud/issues/790)

## Which versions are affected

Please include component versions and any versioning information that is relevant
to reproduce.

## Reproducer steps

Logical enumerated sequence on how to reproduce the issue.

## Example code or configuration

```
Configuration or code that reproduces the issue
```

## Expected behavior

Please explain what should happen

## Current behavior

Please explain the current behavior

*Disclaimer: Please do not create a Pull Request without creating an issue first.*
Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the pull request.

### PR DESCRIPTION
**Pull request by gabrielbussolo**
# Summary of this proposal

closes #193, needs variables applied to test

## Issue(s) number(s)

*Disclaimer: Please do not create a Pull Request without creating an issue first.*

## Checklist for submitter

- [ ] My PR has a related issue/bug number.
- [ ] My PR provides tests
  - [ ] Integration tests are added/passes
  - [ ] Unit tests are added/passes
  - [ ] End-to-end tests added/passes
  - [ ] Static code check added/passes
  - [ ] Linting on documentation added/passes
  - [ ] Does not affect code coverage stats
- [ ] My PR requires updating dependencies
- [ ] My PR has the documentation changes required.

## Checklist for reviewer

- [ ] The proposal fixes a bug/issue or implements a new feature that is well described.
- [ ] The proposal has sufficient test cases that covers the changes.
  - [ ] If changes an API, it does not break backwards compatibility (-1 major version).
- [ ] If integration is required, the proposal has integration tests.
- [ ] The proposal does not break coverage stats
- [ ] The proposal has the required documentation changes.

## Backport

- [ ] Backport to the latest stable release.

### CODE REVIEW

**Review by builtbyproxy — DISMISSED** [review]

**Review by patrick-stephens — DISMISSED** [review]
Looks good, just need to add the secrets themselves now! Let's raise an issue on calyptia/infra to do it

**Comment by patrick-stephens** [comment]
What's up with the lint failures?

**Comment by patrick-stephens** [comment]
@gabrielbussolo can you resolve the linting failures here? https://github.com/calyptia/api/actions/runs/4013124738/jobs/6973486630#step:5:27

**Comment by patrick-stephens** [comment]
Please also add the Shellcheck linter as we're using shell scripts in this repo.
https://github.com/calyptia/core/blob/54dc1b1418476b35fe13020c6c6da025f29e3083/.github/workflows/lint.yml#L16-L21

**Review by trystendsmyth — DISMISSED** [review]
Appears to be basic assignment of secrets to docker testing image, so LGTM as far as I know so far :)

**Review by patrick-stephens — APPROVED** [review]

**Pull request merged**
